version: '3.4'
services:
  ticket-upgrade-prediction:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    command: /bin/sh -c "while sleep 10000; do :; done"