name: "Ensure code quality"

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - '/**'

jobs:
  build:
    name: Build wec
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run code qualit checkcs
        run: bash lint.sh